/**
 * UYEA 全局配置文件
 * 集中管理所有URL、API、路径、超时等配置
 * 更新此文件以改变应用行为，无需修改其他文件
 */

const UYEA_CONFIG = {
  // 资源路径（统一管理，避免重复定义）
  paths: {
    css: '/CSS/',
    js: '/JS/',
    json: '/JSON/',
    icons: '/IMAGE/ICO/',
    images: '/IMAGE/JPG/',
  },

  // 便捷访问（从 paths 派生，保持向后兼容）
  get iconBase() { return this.paths.icons; },
  get iconBaseFallback() { return this.paths.icons; },
  get backgroundBase() { return this.paths.images; },

  // API 配置
  api: {
    // 节假日 API
    holiday: {
      url: 'https://timor.tech/api/holiday/year/',
      timeout: 5000, // 毫秒
      retryTimes: 1, // 重试次数
    },
  },

  // 本地数据文件
  dataFiles: {
    navigation: '/JSON/navigation.json',
    posts: '/JSON/posts.json',
  },

  // 超时配置（毫秒）
  timeouts: {
    fetch: 8000,
    apiHoliday: 5000,
  },

  // localStorage 键前缀（避免冲突）
  storagePrefix: 'uyea_',

  // 存储键名
  storageKeys: {
    language: 'lang',
    searchEngine: 'engine',
    theme: 'theme',
    session: 'session',
    users: 'users_override'
  },

  // 默认语言
  defaultLanguage: 'zh-CN',

  // 默认搜索引擎
  defaultSearchEngine: 'baidu',

  // 搜索引擎URL
  searchEngines: {
    site: null,
    baidu: 'https://www.baidu.com/s?wd=',
    google: 'https://www.google.com/search?q=',
    bing: 'https://cn.bing.com/search?q='
  },

  // 国际化翻译数据
  i18n: {
    'zh-CN': {
      'nav.home': '网站导航',
      'nav.tools': '线上工具',
      'nav.forum': '悠野社区',
      'btn.register': '注册',
      'section.ai': 'AI',
      'section.life': '生活',
      'section.tools': '工具',
      'section.creative': '设计',
      'section.social': '社区',
      'section.shopping': '购物',
      'section.news': '资讯',
      'section.dev': '开发者工具',
      'section.design': '设计美化',
      'section.office': '办公效率',
      'section.media': '多媒体处理',
      'section.text': '文本工具',
      'section.gen': '生成工具',
      'section.convert': '转换工具',
      'section.net': '网络工具',
      'forum.subtitle': '分享 AI 心得、工具作品与生活点滴',
      'nav.subtitle': 'AI、生活、工具网站导航',
      'tools.subtitle': '纯前端在线工具，开箱即用，数据不出本地',
      'forum.cat.announcement': '公告',
      'forum.cat.ai': 'AI 探讨',
      'forum.cat.tools': '工具',
      'forum.cat.life': '生活',
      'forum.cat.feedback': '反馈',
      'forum.newPost': '发布新帖',
      'forum.searchPlaceholder': '搜索帖子、话题或用户...',
      'forum.noResults': '未找到匹配的帖子',
      'forum.failed': '帖子数据加载失败',
      'search.placeholder': '输入关键词搜索...',
      'search.engine.baidu': '百度',
      'search.engine.google': 'Google',
      'search.engine.bing': 'Bing',
      'search.engine.site': '站内',
      'search.resultsTitle': '站内搜索结果',
      'search.resultsCount': '关键词「{q}」共找到 {n} 条结果',
      'search.loading': '搜索中...',
      'search.back': '返回',
      'search.section.forum': '论坛',
      'search.section.nav': '导航',
      'search.section.tools': '工具',
      'search.noResults': '未找到匹配结果',
      'bottom.recommend': '推荐',
      'bottom.follow': '关注',
      'bottom.favorite': '收藏',
      'bottom.qa': '答疑',
      'bottom.resources': '资源',
      'bottom.all': '全部',
      'bottom.ai': 'AI',
      'bottom.social': '社区',
      'bottom.tools': '工具',
      'bottom.creative': '设计',
      'bottom.shopping': '购物',
      'bottom.news': '资讯',
      'bottom.life': '生活',
      'bottom.dev': '开发',
      'bottom.design': '设计',
      'bottom.office': '办公',
      'bottom.media': '媒体',
      'bottom.text': '文本',
      'bottom.gen': '生成',
      'bottom.convert': '转换',
      'bottom.net': '网络',
      'more.text': '更多',
      'nav.addSite': '添加网站',
      'tools.addTool': '添加工具',
      'nav.searchPlaceholder': '搜索网站名称...',
      'tools.searchPlaceholder': '搜索工具名称...',
      'nav.noResults': '未找到匹配的网站',
      'tools.noResults': '未找到匹配的工具',
      'auth.login': '登录',
      'auth.register': '注册',
      'auth.welcomeBack': '欢迎回来',
      'auth.createAccount': '创建新账户',
      'auth.logout': '退出登录',
      'auth.profile': '个人中心',
      'auth.username': '用户名',
      'auth.email': '邮箱',
      'auth.emailPlaceholder': '请输入邮箱地址',
      'auth.password': '密码',
      'auth.nickname': '昵称',
      'auth.confirmPassword': '确认密码',
      'auth.usernamePlaceholder': '请输入用户名',
      'auth.passwordPlaceholder': '请输入密码',
      'auth.nicknamePlaceholder': '请输入昵称（可选）',
      'auth.confirmPasswordPlaceholder': '请再次输入密码',
      'auth.togglePassword': '显示/隐藏密码',
      'auth.noAccount': '还没有账号？',
      'auth.hasAccount': '已有账号？',
      'auth.loggingIn': '登录中...',
      'auth.registering': '注册中...',
      'auth.loginSuccess': '登录成功',
      'auth.registerSuccess': '注册成功',
      'auth.demoHint': '演示账号请在浏览器控制台输入 UYEA.demo() 获取',
      'auth.roleAdmin': '管理员',
      'auth.roleUser': '普通用户',
      'auth.loginTime': '登录时间',
      'auth.errorUsernameRequired': '请输入用户名',
      'auth.errorEmailRequired': '请输入邮箱地址',
      'auth.errorPasswordRequired': '请输入密码',
      'auth.errorUserNotFound': '用户不存在',
      'auth.errorPasswordWrong': '密码错误',
      'auth.errorUsernameTooShort': '用户名至少2个字符',
      'auth.errorUsernameInvalid': '用户名只能包含字母、数字和下划线',
      'auth.errorPasswordTooShort': '密码至少6个字符',
      'auth.errorPasswordMismatch': '两次输入的密码不一致',
      'auth.errorUserExists': '该用户名已被注册',
      'auth.errorNetwork': '网络错误，请稍后重试',
      'auth.underDevelopment': '正在开发中...',
      'toast.comingSoon': '正在完善中',
      'toast.comingSoonDesc': '该功能正在开发中，敬请期待',
      'toast.register': '注册功能正在完善中，敬请期待',
      'toast.loginNotFound': '登录功能正在完善中，敬请期待',
      'toast.addSite': '添加网站功能正在开发中',
      'toast.addTool': '添加工具功能正在开发中',
      'homepage.title': '设为浏览器首页',
      'homepage.intro': '将 UYEA 设为浏览器首页或新标签页，每次打开浏览器即可快速访问。',
      'homepage.chrome.step1': '点击右上角「⋯」菜单，选择「设置」',
      'homepage.chrome.step2': '在「启动时」选择「打开特定网页」',
      'homepage.chrome.step3': '粘贴下方网址并保存',
      'homepage.firefox.step1': '点击右上角「≡」菜单，选择「设置」',
      'homepage.firefox.step2': '在「主页」栏目中粘贴下方网址',
      'homepage.firefox.step3': '选择「自定义网址」即可',
      'homepage.safari.step1': '在「Safari > 设置 > 通用」中设置主页',
      'homepage.safari.step2': '将下方网址粘贴到主页字段',
      'homepage.mobile.title': '手机浏览器',
      'homepage.mobile.step1': '在浏览器设置中找到「主页/起始页」选项',
      'homepage.mobile.step2': '粘贴下方网址即可设为首页',
      'homepage.copyUrl': '复制网址',
      'homepage.copied': '已复制',
      'homepage.note': '提示：也可将本站添加到书签栏，一键快速访问。',
      'homepage.tab.desktop': '桌面端',
      'homepage.tab.mobile': '移动端',
      'homepage.detected': '检测到您正在使用',
      'homepage.followSteps': '请参考以下步骤设置',
      'homepage.otherBrowsers': '其他浏览器',
      'homepage.scrollHint': '左右滑动查看更多浏览器'
    },
    'zh-TW': {
      'nav.home': '網站導航',
      'nav.tools': '線上工具',
      'nav.forum': '悠野社區',
      'btn.register': '註冊',
      'section.ai': 'AI',
      'section.life': '生活',
      'section.tools': '工具',
      'section.creative': '設計',
      'section.social': '社區',
      'section.shopping': '購物',
      'section.news': '資訊',
      'section.dev': '開發者工具',
      'section.design': '設計美化',
      'section.office': '辦公效率',
      'section.media': '多媒體處理',
      'section.text': '文本工具',
      'section.gen': '生成工具',
      'section.convert': '轉換工具',
      'section.net': '網絡工具',
      'forum.subtitle': '分享 AI 心得、工具作品與生活點滴',
      'nav.subtitle': 'AI、生活、工具網站導航',
      'tools.subtitle': '純前端線上工具，開箱即用，數據不出本地',
      'forum.cat.announcement': '公告',
      'forum.cat.ai': 'AI 探討',
      'forum.cat.tools': '工具',
      'forum.cat.life': '生活',
      'forum.cat.feedback': '反饋',
      'forum.newPost': '發佈新帖',
      'forum.searchPlaceholder': '搜索帖子、話題或用戶...',
      'forum.noResults': '未找到匹配的帖子',
      'forum.failed': '帖子數據加載失敗',
      'search.placeholder': '輸入關鍵詞搜索...',
      'search.engine.baidu': '百度',
      'search.engine.google': 'Google',
      'search.engine.bing': 'Bing',
      'search.engine.site': '站內',
      'search.resultsTitle': '站內搜索結果',
      'search.resultsCount': '關鍵詞「{q}」共找到 {n} 條結果',
      'search.loading': '搜索中...',
      'search.back': '返回',
      'search.section.forum': '論壇',
      'search.section.nav': '導航',
      'search.section.tools': '工具',
      'search.noResults': '未找到匹配結果',
      'bottom.recommend': '推薦',
      'bottom.follow': '關注',
      'bottom.favorite': '收藏',
      'bottom.qa': '答疑',
      'bottom.resources': '資源',
      'bottom.all': '全部',
      'bottom.ai': 'AI',
      'bottom.social': '社區',
      'bottom.tools': '工具',
      'bottom.creative': '設計',
      'bottom.shopping': '購物',
      'bottom.news': '資訊',
      'bottom.life': '生活',
      'bottom.dev': '開發',
      'bottom.design': '設計',
      'bottom.office': '辦公',
      'bottom.media': '媒體',
      'bottom.text': '文本',
      'bottom.gen': '生成',
      'bottom.convert': '轉換',
      'bottom.net': '網絡',
      'more.text': '更多',
      'nav.addSite': '添加網站',
      'tools.addTool': '添加工具',
      'nav.searchPlaceholder': '搜索網站名稱...',
      'tools.searchPlaceholder': '搜索工具名稱...',
      'nav.noResults': '未找到匹配的網站',
      'tools.noResults': '未找到匹配的工具',
      'auth.login': '登入',
      'auth.register': '註冊',
      'auth.welcomeBack': '歡迎回來',
      'auth.createAccount': '建立新帳戶',
      'auth.logout': '登出',
      'auth.profile': '個人中心',
      'auth.username': '用戶名',
      'auth.email': '郵箱',
      'auth.emailPlaceholder': '請輸入郵箱地址',
      'auth.password': '密碼',
      'auth.nickname': '暱稱',
      'auth.confirmPassword': '確認密碼',
      'auth.usernamePlaceholder': '請輸入用戶名',
      'auth.passwordPlaceholder': '請輸入密碼',
      'auth.nicknamePlaceholder': '請輸入暱稱（可選）',
      'auth.confirmPasswordPlaceholder': '請再次輸入密碼',
      'auth.togglePassword': '顯示/隱藏密碼',
      'auth.noAccount': '還沒有帳號？',
      'auth.hasAccount': '已有帳號？',
      'auth.loggingIn': '登入中...',
      'auth.registering': '註冊中...',
      'auth.loginSuccess': '登入成功',
      'auth.registerSuccess': '註冊成功',
      'auth.demoHint': '演示帳號請在瀏覽器控制台輸入 UYEA.demo() 獲取',
      'auth.roleAdmin': '管理員',
      'auth.roleUser': '普通用戶',
      'auth.loginTime': '登入時間',
      'auth.errorUsernameRequired': '請輸入用戶名',
      'auth.errorEmailRequired': '請輸入郵箱地址',
      'auth.errorPasswordRequired': '請輸入密碼',
      'auth.errorUserNotFound': '用戶不存在',
      'auth.errorPasswordWrong': '密碼錯誤',
      'auth.errorUsernameTooShort': '用戶名至少2個字符',
      'auth.errorUsernameInvalid': '用戶名只能包含字母、數字和下劃線',
      'auth.errorPasswordTooShort': '密碼至少6個字符',
      'auth.errorPasswordMismatch': '兩次輸入的密碼不一致',
      'auth.errorUserExists': '該用戶名已被註冊',
      'auth.errorNetwork': '網絡錯誤，請稍後重試',
      'auth.underDevelopment': '正在開發中...',
      'toast.comingSoon': '正在完善中',
      'toast.comingSoonDesc': '該功能正在開發中，敬請期待',
      'toast.register': '註冊功能正在完善中，敬請期待',
      'toast.loginNotFound': '登入功能正在完善中，敬請期待',
      'toast.addSite': '添加網站功能正在開發中',
      'toast.addTool': '添加工具功能正在開發中',
      'homepage.title': '設為瀏覽器首頁',
      'homepage.intro': '將 UYEA 設為瀏覽器首頁或新分頁，每次打開瀏覽器即可快速訪問。',
      'homepage.chrome.step1': '點擊右上角「⋯」選單，選擇「設定」',
      'homepage.chrome.step2': '在「啟動時」選擇「打開特定網頁」',
      'homepage.chrome.step3': '貼上下方網址並儲存',
      'homepage.firefox.step1': '點擊右上角「≡」選單，選擇「設定」',
      'homepage.firefox.step2': '在「首頁」欄目中貼上下方網址',
      'homepage.firefox.step3': '選擇「自訂網址」即可',
      'homepage.safari.step1': '在「Safari > 設定 > 一般」中設定首頁',
      'homepage.safari.step2': '將下方網址貼到首頁欄位',
      'homepage.mobile.title': '手機瀏覽器',
      'homepage.mobile.step1': '在瀏覽器設定中找到「首頁/起始頁」選項',
      'homepage.mobile.step2': '貼上下方網址即可設為首頁',
      'homepage.copyUrl': '複製網址',
      'homepage.copied': '已複製',
      'homepage.note': '提示：也可將本站加入書籤列，一鍵快速訪問。',
      'homepage.tab.desktop': '桌面端',
      'homepage.tab.mobile': '移動端',
      'homepage.detected': '檢測到您正在使用',
      'homepage.followSteps': '請參考以下步驟設置',
      'homepage.otherBrowsers': '其他瀏覽器',
      'homepage.scrollHint': '左右滑動查看更多瀏覽器'
    },
    'en': {
      'nav.home': 'Navigation',
      'nav.tools': 'Tools',
      'nav.forum': 'Community',
      'btn.register': 'Register',
      'section.ai': 'AI',
      'section.life': 'Lifestyle',
      'section.tools': 'Tools',
      'section.creative': 'Design',
      'section.social': 'Community',
      'section.shopping': 'Shopping',
      'section.news': 'News',
      'section.dev': 'Developer Tools',
      'section.design': 'Design',
      'section.office': 'Office',
      'section.media': 'Media',
      'section.text': 'Text Tools',
      'section.gen': 'Generators',
      'section.convert': 'Converters',
      'section.net': 'Network',
      'forum.subtitle': 'Share AI insights, tool creations & life moments',
      'nav.subtitle': 'AI, lifestyle & tools directory',
      'tools.subtitle': 'Pure front-end online tools, ready to use, data stays local',
      'forum.cat.announcement': 'Announcements',
      'forum.cat.ai': 'AI Discussion',
      'forum.cat.tools': 'Tools',
      'forum.cat.life': 'Lifestyle',
      'forum.cat.feedback': 'Feedback',
      'forum.newPost': 'New Post',
      'forum.searchPlaceholder': 'Search posts, topics or users...',
      'forum.noResults': 'No matching posts found',
      'forum.failed': 'Failed to load posts',
      'search.placeholder': 'Enter keywords to search...',
      'search.engine.baidu': 'Baidu',
      'search.engine.google': 'Google',
      'search.engine.bing': 'Bing',
      'search.engine.site': 'Site',
      'search.resultsTitle': 'Site Search Results',
      'search.resultsCount': 'Keyword "{q}" found {n} results',
      'search.loading': 'Searching...',
      'search.back': 'Back',
      'search.section.forum': 'Forum',
      'search.section.nav': 'Navigation',
      'search.section.tools': 'Tools',
      'search.noResults': 'No matching results found',
      'bottom.recommend': 'Recommend',
      'bottom.follow': 'Following',
      'bottom.favorite': 'Favorites',
      'bottom.qa': 'Q&A',
      'bottom.resources': 'Resources',
      'bottom.all': 'All',
      'bottom.ai': 'AI',
      'bottom.social': 'Social',
      'bottom.tools': 'Tools',
      'bottom.creative': 'Design',
      'bottom.shopping': 'Shop',
      'bottom.news': 'News',
      'bottom.life': 'Life',
      'bottom.dev': 'Dev',
      'bottom.design': 'Design',
      'bottom.office': 'Office',
      'bottom.media': 'Media',
      'bottom.text': 'Text',
      'bottom.gen': 'Gen',
      'bottom.convert': 'Convert',
      'bottom.net': 'Net',
      'more.text': 'More',
      'nav.addSite': 'Add Site',
      'tools.addTool': 'Add Tool',
      'nav.searchPlaceholder': 'Search site names...',
      'tools.searchPlaceholder': 'Search tool names...',
      'nav.noResults': 'No matching sites found',
      'tools.noResults': 'No matching tools found',
      'auth.login': 'Login',
      'auth.register': 'Register',
      'auth.welcomeBack': 'Welcome back',
      'auth.createAccount': 'Create a new account',
      'auth.logout': 'Logout',
      'auth.profile': 'Profile',
      'auth.username': 'Username',
      'auth.email': 'Email',
      'auth.emailPlaceholder': 'Enter email address',
      'auth.password': 'Password',
      'auth.nickname': 'Nickname',
      'auth.confirmPassword': 'Confirm Password',
      'auth.usernamePlaceholder': 'Enter username',
      'auth.passwordPlaceholder': 'Enter password',
      'auth.nicknamePlaceholder': 'Enter nickname (optional)',
      'auth.confirmPasswordPlaceholder': 'Enter password again',
      'auth.togglePassword': 'Show/Hide password',
      'auth.noAccount': "Don't have an account?",
      'auth.hasAccount': 'Already have an account?',
      'auth.loggingIn': 'Logging in...',
      'auth.registering': 'Registering...',
      'auth.loginSuccess': 'Login successful',
      'auth.registerSuccess': 'Registration successful',
      'auth.demoHint': 'For demo account, run UYEA.demo() in browser console',
      'auth.roleAdmin': 'Administrator',
      'auth.roleUser': 'User',
      'auth.loginTime': 'Login Time',
      'auth.errorUsernameRequired': 'Please enter username',
      'auth.errorEmailRequired': 'Please enter email address',
      'auth.errorPasswordRequired': 'Please enter password',
      'auth.errorUserNotFound': 'User not found',
      'auth.errorPasswordWrong': 'Wrong password',
      'auth.errorUsernameTooShort': 'Username must be at least 2 characters',
      'auth.errorUsernameInvalid': 'Username can only contain letters, numbers and underscores',
      'auth.errorPasswordTooShort': 'Password must be at least 6 characters',
      'auth.errorPasswordMismatch': 'Passwords do not match',
      'auth.errorUserExists': 'Username already taken',
      'auth.errorNetwork': 'Network error, please try again later',
      'auth.underDevelopment': 'Under development...',
      'toast.comingSoon': 'Coming Soon',
      'toast.comingSoonDesc': 'This feature is under development, stay tuned',
      'toast.register': 'Registration is under development, stay tuned',
      'toast.loginNotFound': 'Login is under development, stay tuned',
      'toast.addSite': 'Add site feature is under development',
      'toast.addTool': 'Add tool feature is under development',
      'homepage.title': 'Set as Browser Homepage',
      'homepage.intro': 'Set UYEA as your browser homepage or new tab page for quick access every time you open your browser.',
      'homepage.chrome.step1': 'Click the "⋯" menu in the top right, select "Settings"',
      'homepage.chrome.step2': 'Under "On startup", select "Open a specific page"',
      'homepage.chrome.step3': 'Paste the URL below and save',
      'homepage.firefox.step1': 'Click the "≡" menu in the top right, select "Settings"',
      'homepage.firefox.step2': 'Under "Home", paste the URL below',
      'homepage.firefox.step3': 'Select "Custom URL" option',
      'homepage.safari.step1': 'Go to "Safari > Settings > General" to set homepage',
      'homepage.safari.step2': 'Paste the URL below into the homepage field',
      'homepage.mobile.title': 'Mobile Browser',
      'homepage.mobile.step1': 'Find "Homepage/Start page" in browser settings',
      'homepage.mobile.step2': 'Paste the URL below to set as homepage',
      'homepage.copyUrl': 'Copy URL',
      'homepage.copied': 'Copied',
      'homepage.note': 'Tip: You can also bookmark this site for one-click access.',
      'homepage.tab.desktop': 'Desktop',
      'homepage.tab.mobile': 'Mobile',
      'homepage.detected': 'Detected: You are using',
      'homepage.followSteps': 'Follow these steps to set up',
      'homepage.otherBrowsers': 'Other Browsers',
      'homepage.scrollHint': 'Swipe to see more browsers'
    }
  },

  /**
   * 获取存储键（带前缀）
   * @param {string} key 键名
   * @returns {string} 带前缀的键名
   */
  getStorageKey: function(key) {
    return UYEA_CONFIG.storagePrefix + key;
  },

  /**
   * 获取搜索引擎URL
   * @param {string} engine 搜索引擎代码
   * @returns {string|null} URL模板或null
   */
  getSearchEngineUrl: function(engine) {
    // 注意：site 引擎的值为 null（表示站内搜索），不能用 || 判断
    // 仅当引擎不存在于对象中时才回退到默认引擎
    var url = UYEA_CONFIG.searchEngines[engine];
    return url !== undefined ? url : UYEA_CONFIG.searchEngines.baidu;
  },

  /**
   * 获取翻译
   * @param {string} lang 语言代码
   * @param {string} key 翻译键
   * @returns {string} 翻译内容
   */
  getTranslation: function(lang, key) {
    const msgs = UYEA_CONFIG.i18n[lang] || UYEA_CONFIG.i18n[UYEA_CONFIG.defaultLanguage];
    return msgs[key] || key;
  }
};

// 挂载到 window 供其他模块通过 window.UYEA_CONFIG 访问
if (typeof window !== 'undefined') {
  window.UYEA_CONFIG = UYEA_CONFIG;
}

// 兼容性导出
if (typeof module !== 'undefined' && module.exports) {
  module.exports = UYEA_CONFIG;
}
